- name: Install nginx
  hosts: all
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Copy index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: 0644
    - name: Restart nginx
      service:
        name: nginx
        state: restarted